### ISSUE TITLE
Problem in add Image plugin (Image.coffee) to annotator!

### ISSUE THREAD

**Issue by 88107251** [uq-eresearch/annotator#4]
I was compiled image.coffee plugin to image.js and want to add this to okfn annotator but when this plugin add to annotator and run it this error is shown:

this.annotator.addAnnotationPlugin is not a function (Line 31 in image.coffee)

please help me to resolve this problem.

**Comment by omad** [comment]
The Image plugin currently requires modifications to the core annotator.coffee (hence the missing function). I'm planning on rewriting it to work with stock annotator.

For the time being, either use our modified annotator, or have a look at https://github.com/annotorious/annotorious/blob/master/src/okfn/okfn_image_plugin.js which is an alternative image annotation plugin. It doesn't appear to be a simple drop in either.
